## Default application configuration

workerConfiguration:

  test: hello

  #The next line is for Swagger
  resourcePackage: com.usermind.usermindsdk.dropwizard.urlhandlers

#Hopefully soon we can tell Swagger not to scan every file -
#https://github.com/swagger-api/swagger-core/issues/2631

server:
  applicationConnectors:
    - type: http
      port: 8089

  adminConnectors:
    - type: http
      port: 8090

logging:
  level: DEBUG
  loggers:
    "com.usermind": DEBUG
    "org.apache.http.wire" : INFO
    "org.apache.http.headers" : INFO
    "org.reflections" : ERROR
  appenders:
    - type: console
      target: stdout
# This logs in JSON which does nice things for ElasticSearch and other tools. If you don't want to log in JSON,
# uncomment the two lines below and remove the Layout section.
#      timeZone: UTC
#      logFormat: "%-5p [%d{ISO8601, UTC}] [%thread] %c: %m%n%xEx"
      layout:
        type: json
        timestampFormat: "ISO_INSTANT"
        prettyPrint: false
        appendLineSeparator: true
