#!/bin/bash

# Remember to make this file executable with a chmod u+x
# This is used to run the given docker image locally.
# -e for declaring environment variables.
# -v used for vloume mounting
# -p expose port
# -it allocates a tty

docker run -it \
  -v $PWD:/app \
  -p 8089:8089 \
  usermindinc/integrations-sdktemplate:1.0.0-SNAPSHOT
