Kubernetes Secrets:
apiVersion: v1
data:
 # <key for env var>: <value for env var base64 encoded>
kind: Secret
metadata:
 name: integrations-sdk-sdktemplate-secrets
 namespace: integrations
 selfLink: /api/v1/namespaces/integrations/secrets/integrations-sdk-sdktemplate-secrets
type: Opaque
