kind: Service
apiVersion: v1
metadata:
  name: integrations-tito
  namespace: integrations
 
spec:
  selector:
    app: integrations-tito
  ports:
    - name: http
      protocol: "TCP"
      port: 8089
      targetPort: 8089
  type: LoadBalancer
