kind: Service
apiVersion: v1
metadata:
  name: integrations-sdktemplate
  namespace: integrations
 
spec:
  selector:
    app: integrations-sdktemplate
  ports:
    - name: http
      protocol: "TCP"
      port: 8089
      targetPort: 8089
  type: LoadBalancer
