/*
 * Decompiled with CFR 0_125.
 */
package com.usermind.usermindsdk.worker.autogen.lc39;

import com.usermind.usermindsdk.worker.autogen.lc39.tables.ActionJournalStatus;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Actionargs;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Actionjournal;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Actions;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Channelentities;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Channels;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Cronstate;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.CustomerStatus;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Databasechangelog;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Emailconfigurations;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Entities;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Entitygraphs;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Entityinstanceedges;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Entityinstances;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Entitytravelermap;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Execguardstate;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.FaqwadMessages;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.FaqwadQueueDefinitions;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.FaqwadStates;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.FaqwadTypes;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Fetchrecords;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Fields;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Integrationconfigs;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Journeys;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Journeystates;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Latestjourneys;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Maps;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Milestones;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Organizations;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Picklistitems;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Proctriggers;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Rules;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Smilestones;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Staticentitymapspecification;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Staticentitymetadata;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Tickschedules;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.TravelerEventStates;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.TravelerEventTypes;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.TravelerEvents;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Travelerchannels;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Travelerrulestate;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Travelers;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Travelerstate;
import com.usermind.usermindsdk.worker.autogen.lc39.tables.Umtransactions;

public class Tables {
    public static final Actionargs ACTIONARGS = Actionargs.ACTIONARGS;
    public static final Actionjournal ACTIONJOURNAL = Actionjournal.ACTIONJOURNAL;
    public static final Actions ACTIONS = Actions.ACTIONS;
    public static final Channelentities CHANNELENTITIES = Channelentities.CHANNELENTITIES;
    public static final Channels CHANNELS = Channels.CHANNELS;
    public static final Cronstate CRONSTATE = Cronstate.CRONSTATE;
    public static final Emailconfigurations EMAILCONFIGURATIONS = Emailconfigurations.EMAILCONFIGURATIONS;
    public static final Entities ENTITIES = Entities.ENTITIES;
    public static final Entitygraphs ENTITYGRAPHS = Entitygraphs.ENTITYGRAPHS;
    public static final Entityinstanceedges ENTITYINSTANCEEDGES = Entityinstanceedges.ENTITYINSTANCEEDGES;
    public static final Entityinstances ENTITYINSTANCES = Entityinstances.ENTITYINSTANCES;
    public static final Entitytravelermap ENTITYTRAVELERMAP = Entitytravelermap.ENTITYTRAVELERMAP;
    public static final Execguardstate EXECGUARDSTATE = Execguardstate.EXECGUARDSTATE;
    public static final Fetchrecords FETCHRECORDS = Fetchrecords.FETCHRECORDS;
    public static final Fields FIELDS = Fields.FIELDS;
    public static final Integrationconfigs INTEGRATIONCONFIGS = Integrationconfigs.INTEGRATIONCONFIGS;
    public static final Journeystates JOURNEYSTATES = Journeystates.JOURNEYSTATES;
    public static final Journeys JOURNEYS = Journeys.JOURNEYS;
    public static final Latestjourneys LATESTJOURNEYS = Latestjourneys.LATESTJOURNEYS;
    public static final Maps MAPS = Maps.MAPS;
    public static final Milestones MILESTONES = Milestones.MILESTONES;
    public static final Organizations ORGANIZATIONS = Organizations.ORGANIZATIONS;
    public static final Picklistitems PICKLISTITEMS = Picklistitems.PICKLISTITEMS;
    public static final Proctriggers PROCTRIGGERS = Proctriggers.PROCTRIGGERS;
    public static final Rules RULES = Rules.RULES;
    public static final Smilestones SMILESTONES = Smilestones.SMILESTONES;
    public static final Staticentitymapspecification STATICENTITYMAPSPECIFICATION = Staticentitymapspecification.STATICENTITYMAPSPECIFICATION;
    public static final Staticentitymetadata STATICENTITYMETADATA = Staticentitymetadata.STATICENTITYMETADATA;
    public static final Tickschedules TICKSCHEDULES = Tickschedules.TICKSCHEDULES;
    public static final Travelerchannels TRAVELERCHANNELS = Travelerchannels.TRAVELERCHANNELS;
    public static final Travelerrulestate TRAVELERRULESTATE = Travelerrulestate.TRAVELERRULESTATE;
    public static final Travelerstate TRAVELERSTATE = Travelerstate.TRAVELERSTATE;
    public static final Travelers TRAVELERS = Travelers.TRAVELERS;
    public static final Umtransactions UMTRANSACTIONS = Umtransactions.UMTRANSACTIONS;
    public static final ActionJournalStatus ACTION_JOURNAL_STATUS = ActionJournalStatus.ACTION_JOURNAL_STATUS;
    public static final CustomerStatus CUSTOMER_STATUS = CustomerStatus.CUSTOMER_STATUS;
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;
    public static final FaqwadMessages FAQWAD_MESSAGES = FaqwadMessages.FAQWAD_MESSAGES;
    public static final FaqwadQueueDefinitions FAQWAD_QUEUE_DEFINITIONS = FaqwadQueueDefinitions.FAQWAD_QUEUE_DEFINITIONS;
    public static final FaqwadStates FAQWAD_STATES = FaqwadStates.FAQWAD_STATES;
    public static final FaqwadTypes FAQWAD_TYPES = FaqwadTypes.FAQWAD_TYPES;
    public static final TravelerEventStates TRAVELER_EVENT_STATES = TravelerEventStates.TRAVELER_EVENT_STATES;
    public static final TravelerEventTypes TRAVELER_EVENT_TYPES = TravelerEventTypes.TRAVELER_EVENT_TYPES;
    public static final TravelerEvents TRAVELER_EVENTS = TravelerEvents.TRAVELER_EVENTS;
}

